/* 🧪 Test de regresión del chat de WALLY — ejecutar: node test_wally_chat.js
   Extrae la función wallyReply de index.html, la ejecuta en Node con stubs (localStorage, $, toast...)
   y comprueba que cada pregunta cae en el handler correcto (los handlers se evalúan en orden y
   una palabra puede ser capturada por otro comando: esto lo detecta antes de publicar). */
const fs=require("fs"); const path=require("path");
const s=fs.readFileSync(path.join(__dirname,"index.html"),"utf8");
const st=s.indexOf("function wallyReply(q){"); if(st<0){ console.error("no se encontró wallyReply"); process.exit(2); }
let depth=0, end=-1;
for(let j=s.indexOf("{",st); j<s.length; j++){ const c=s[j]; if(c==="{") depth++; else if(c==="}"){ depth--; if(depth===0){ end=j; break; } } }
const src=s.slice(st,end+1);
const store={};
const localStorage={getItem:k=>(k in store?store[k]:null),setItem:(k,v)=>{store[k]=String(v);},removeItem:k=>{delete store[k];}};
const window={localStorage,_wallyPrevQ:""}; window.wallyName=()=>localStorage.getItem("edtu_agent_name")||"";   /* stub del nombre (se define fuera de wallyReply) */
const $=()=>null; const g=k=>localStorage.getItem(k); const pick=a=>a[0]; const toast=()=>{}; const wallyType=()=>{};
const navigator={userAgent:"node"}; const document={getElementById:()=>null,querySelectorAll:()=>[]};
const fmtMS=t=>Math.floor(t/60)+":"+String(Math.floor(t%60)).padStart(2,"0");
let fn;
try{ fn=new Function("localStorage","window","$","g","pick","toast","wallyType","navigator","document","fmtMS","setTimeout","speechSynthesis", src+"; return wallyReply;")(localStorage,window,$,g,pick,toast,wallyType,navigator,document,fmtMS,()=>0,undefined); }
catch(e){ console.error("❌ wallyReply no compila:",e.message); process.exit(2); }
/* [pregunta, regex esperado] — en orden (algunas son secuencias: adivinanza→pista→me rindo) */
const T=[
  ["hola",/agente/],["buenos días",/agente/],["ey wally",/agente|oídos|dime|aquí estoy/],["ayuda",/pregúntame por/],
  ["cuánto es 12 por 7",/= 84/],["100 entre 4",/= 25/],["2+2",/= 4/],["4 al cubo",/= 64/],["raíz de 81",/= 9/],["20% de 50",/= 10/],["10/0",/cero/],
  ["tira el dado",/🎲/],["d20",/20 caras/],["2 dados",/= \d+/],["moneda",/🪙/],["cara o sello",/CARA|SELLO/],
  ["qué día es hoy",/📅 hoy es/],["cuánto falta para el finde",/📅/],
  ["trabalenguas",/👅/],
  ["adivinanza",/🧠 adivinanza/],["pista",/💡 pista/],["me rindo",/era «/],
  ["adivina",/1 al 100/],["1000",/entre 1 y 100/],["50",/más (alto|bajo)|🎯/],["me rindo",/./],
  ["al revés anilina",/PALÍNDROMO/],["deletrea dino",/D - I - N - O/],["cómo se escribe murciélago",/10 letras/],["cuenta hasta 5",/1, 2, 3, 4, 5/],
  ["cuenta atrás desde 3",/3\.\.\. 2\.\.\. 1\.\.\. ¡DESPEGUE!/],
  ["piedra",/vs .* → /],["papel",/marcador/],["tijeras",/marcador/],
  ["juegos del chat",/juegos aquí mismo/],["juguemos",/juegos aquí mismo/],
  ["abre jurassic",/abriendo|dime cuál/],["quiero jugar",/dime cuál/],
  ["avísame en 1 minuto",/te aviso en 1 minuto/],["temporizador 30 segundos",/30 segundos/],
  ["canta",/soy WALLY/],["voz",/voz encendida/],["silencio",/voz apagada/],["micrófono",/🎤/],
  ["minijuegos",/🕹️/],["juegos",/./],["cubo",/trucos del CUBO/],["nitro",/trucos de F1/],["antídoto",/trucos de SCREAM/],["pescar",/trucos de JURASSIC/],["zombie",/TORRETA|zombi/i],
  ["mapa",/🧭/],["pausa",/⏸/],["fantasma",/👻/],["hora",/🕐/],["mejoras",/MEJORAS/],["chiste",/./],["estadísticas",/📈/],["calendario",/🗓️/],
  ["quién eres",/soy WALLY/],["quién te creó",/David/],["cuéntame un cuento",/érase una vez/],["tabla del 7",/7×7=49/],
  ["cuánto falta para navidad",/🎄/],["halloween",/🎃/],["cuánto falta para mi cumpleaños",/aún no sé tu cumpleaños/],["mi cumpleaños es el 14 de marzo",/apuntado/],["cuánto falta para mi cumpleaños",/🎂 (faltan|¡tu)/],
  ["cómo me llamo",/aún no sé tu nombre/],["me llamo david",/encantado, David/],["cómo me llamo",/te llamas David/],["olvida mi nombre",/agente/],
  ["marcador del chat",/🏅 marcador del chat/],["marcador",/adivinanzas resueltas/],
  ["cómo estás",/batería|feliz|circuitos/],["qué haces",/vigilo|ordeno|trabalenguas/],["te quiero",/💛|mejor espía/],["eres genial",/💛|mejor espía/],["tienes hambre",/electricidad|despierto|miedo/],["bien",/me alegro|anotado|gracias por/],
  ["mis estadísticas",/💬 chat/],
  ["sabías que",/🧠 ¿sabías que/],["dato curioso",/🧠 ¿sabías que/],
  ["cómo se dice araña en inglés",/spider/],["gato en inglés",/«cat»/],["el dinosaurio en inglés",/dinosaur/],["xyzq en inglés",/diccionario/],
  ["qué más sabes",/💡/],["dame un consejo",/💡/],
  ["quiz de inglés",/🇬🇧 quiz: ¿cómo se dice/],["zzzz",/casi/],["me rindo",/en inglés es/],
  ["trivia",/🧠 trivia: .* a\) /],["b",/CORRECTO|era [abc]\)/],
  ["quiz de mates",/🧮 ¿cuánto es \d+ [+\-×] \d+\?/],["me rindo",/😅 \d+ [+\-×] \d+ = -?\d+/],["quiz de mates fácil",/🧮 ¿cuánto es/],["0",/CORRECTO|casi/],
  ["me rindo",/era \d+|nada de qué rendirse/],["me rindo",/nada de qué rendirse/],
  ["cuántos comandos sabes",/sé responder a unos \d+ tipos/],
  ["mis notas",/🎓 tus notas — 🧮 mates: \d+\/\d+/],["cómo voy en mates",/🎓 tus notas/],
  ["ronda de mates",/RONDA DE 5! pregunta 1 de 5/],["0",/pregunta 2 de 5/],["0",/pregunta 3 de 5/],["0",/pregunta 4 de 5/],["0",/pregunta 5 de 5/],["0",/RONDA TERMINADA: \d\/5/],["ronda de trivia",/RONDA DE 5.*a\) /],["a",/pregunta 2 de 5/],
  ["ronda de inglés",/RONDA DE 5! pregunta 1 de 5: ¿cómo se dice/],["zzzz",/era «.*» ➜ pregunta 2 de 5/],["me rindo",/pregunta 3 de 5/],["me rindo",/pregunta 4 de 5/],["me rindo",/pregunta 5 de 5/],["me rindo",/RONDA TERMINADA: \d\/5/],
  ["mis notas",/mejores rondas: .*mates \d\/5/],
  ["cuéntame otro",/^(?!.*quisiste decir)/],["wally",/dime, agente|aquí estoy|oídos/],["wally!",/dime, agente|aquí estoy|oídos/],["jajaja",/reír|risa|jaja/],["xd",/reír|risa|jaja/],["no",/sin problema|cambias de idea|entendido/],["eres muy lento",/circuitos|dramático|lento yo/],["puedes cantar",/soy WALLY/],["chiste",/./],["sí",/^(?!👍|¡genial|beep 👍)/],["ok",/perfecto|genial|desafío|robot|médico|batería|virus|despide/],
  ["cómo te llamas",/me llamo WALLY/],["dónde vives",/edtu\.cl/],["tienes amigos",/mejor amigo/],["puedes bailar",/baila|gira/],["qué comes",/electricidad/],["cuál es tu color favorito",/azul/],["te gusta el fútbol",/fútbol/],["estoy triste",/lo siento|chiste/],["tengo miedo",/aquí estoy/],["tengo sueño",/descansar/],["qué hago",/ideas:/],["cuántos días tiene un año",/365/],["cuál es la capital de chile",/Santiago/],["capital de japón",/Tokio/],["cuántos juegos hay",/22 juegos/],["hazme una pregunta",/🧠 trivia/],["a",/./],["a",/./],["a",/./],["a",/./],["a",/./],
  ["soy el mejor",/claro que sí/],["cómo pesco",/pesc|JURASSIC/i],["cómo apago la voz",/voz apagada/],["cuántas medallas tengo",/logro|trofeo/i],["qué es wally",/soy WALLY/],["eres chatgpt",/no soy ChatGPT/],["te odio",/circuitos|dramático/],["eres mi mejor amigo",/mejor amigo/],["cuánto falta para el verano",/☀️/],["qué día es mañana",/📅 mañana es/],["qué hora es en españa",/🕐 en España son las \d/],["gané",/GRANDE|eso es|beep-beep/],["me morí",/uf|nada grave|palmadita/],["me llamo david",/encantado, David/],["olvida mi nombre",/agente/],
  ["holi",/agente/],["que onda",/agente/],["como estai",/batería|feliz|circuitos/],["bkn",/💛|mejor espía/],["eres bacán",/💛|mejor espía/],["dame 5",/CHOCA/],["dime algo bonito",/valiente|tesoro|mejor momento/],["modo imposible",/IMPOSIBLE del CUBO/],["cuánto dura scream",/20 minutos/],["cómo gano la carrera",/trucos de F1/],["cómo se juega snake",/Snake|SNAKE/],["cuántas horas he jugado",/horas exactas/],
  ["qué es un espía",/🕵️ un espía de EDTU/],["dame una misión",/🕵️ tu misión/],["qué hice ayer",/📖 lo último/],["mi mejor partida",/./],["cuántos puntos tengo",/no hay niveles/],["cómo comparto",/COMPARTIR/],["dónde estoy",/Sala de Trofeos/],["cómo llamo al helicóptero",/🚁 rescates/],["qué hago con el huevo",/huevo/],
  ["cuéntame algo de ti",/soy WALLY/],["qué hay de nuevo",/MEJORAS/],["novedades",/MEJORAS/],["te acuerdas de mí",/🧠 ¡claro que recuerdo/],["borra todo",/cosa seria/],["cómo borro mi nombre",/olvida mi nombre/],["habla más despacio",/velocidad 0\.9/],["sube el volumen",/volumen 100%/],["velocidad normal",/velocidad 1\.05/],["apaga la música",/no hay música/],["habla en inglés",/a little bit/],["hello",/hello, agent/],["how are you",/I'm great/],["thank you",/welcome/],["10 elevado a 3",/= 1000/],["el doble de 8",/= 16/],["la mitad de 50",/= 25/],["(2+3)*4",/= 20/],["convierte 3 km a metros",/= 3000 metros/],["2 horas a minutos",/= 120 minutos/],["cuántos segundos tiene un día",/86\.400/],
  ["socorro",/🆘 ¡aquí estoy/],["help",/🆘/],["no me funciona",/soporte de WALLY/],["no tengo sonido",/sin sonido/],["cómo instalo edtu",/📲 instalar/],["pantalla completa",/F11/],["cómo juego en el celular",/táctiles/],["funciona con mando",/RT acelera/],["qué teclas uso",/⌨️ controles/],["cómo pauso",/⏸ pausa/],["cómo guardo",/se guarda solo/],["perdí mis récords",/ESTE navegador/],["puedo jugar sin internet",/📴/],["es gratis",/🆓/],["quién hizo los juegos",/David programó/],
  ["chiste de dinos",/tesauro-rex/],["cuántos chistes sabes",/un montón/],["cuánto es pi",/3,14159/],["infinito más uno",/♾️/],["dime un número del 1 al 10",/🎲 \d+ \(entre 1 y 10\)/],["elige entre jurassic y scream",/JURASSIC|SCREAM/],["juguemos a las escondidas",/🙈/],["veo veo",/👀 veo veo/],["pista",/💡 pista: tiene \d+ letras/],["me rindo",/era «/],["piedra papel o tijera",/di 'piedra'/],["cuánto es cero por cero",/= 0/],["cuántos son 3 más 4",/= 7/],["cuánto es 2 elevado a 10",/\(2\^10\) = 1024/],["tabla del 13",/13×7=91/],["tabla del 0",/0×5=0/],["adivinanza",/🧠 adivinanza/],["tabla del 3",/3×3=9/],["me rindo",/era «/],["trivia de dinosaurios",/dinosaurio|T-rex/i],["b",/./],["chiste",/./],["de nuevo",/robot|médico|batería|virus|despide|binario|🎲|chiste/],
  ["qué animal es el más rápido",/guepardo/],["habla más rápido",/velocidad/],["cuántos planetas hay",/8 planetas/],["por qué se extinguieron los dinosaurios",/asteroide/],["qué es un bug",/polilla/],["quién inventó el teléfono",/Meucci/],["qué es javascript",/David me programó/],["quiero aprender a programar",/console\.log/],["cuántos huesos tiene un gato",/230/],["dónde queda chile",/Andes/],
  ["soy niño",/bienvenido a EDTU/],["soy nuevo",/bienvenido a EDTU/],["tutorial",/bienvenido a EDTU/],["tengo 11 años",/David tiene 11/],["adivina mi edad",/tienes 11 años/],["adivina mi nombre",/David\?|te llamas/],["adivina",/1 al 100/],["me rindo",/era \d+/],["qué opinas de jurassic",/🦖 JURASSIC: una isla/],["qué es not a game",/🧟 NOT A GAME/],["de qué se trata f1",/🏎️ F1 RB RUSH/],["cuál es el juego más difícil",/SCREAM/],["cuál es el más fácil",/para empezar/],["dime algo",/./],["shhh",/voz apagada/],["me llamo sofía",/encantado, Sofía/],["olvida mi nombre",/agente/],
  ["buenas noches",/🌙/],["feliz cumpleaños wally",/MEJORAS/],["feliz año nuevo",/🎆/],["tengo que irme",/te espero|a la orden|pausa de agente/],["volví",/volviste/],["perdón",/no pasa nada|perdonado|tranqui/],["gracias por el chiste",/de nada|placer|gracias a ti/],["muy bueno",/gracias|sonroja|me alegra/],["no me gustó",/va otro/],["muy difícil",/😈/],["no puedo",/casi|nada es imposible|respira/],["qué es el sigilo",/SIGILO/],["dame una pista",/pista de qué/],
  ["dame un reto",/⚔️ tu reto/],["hay premios",/DESAFÍO DEL DÍA: cada día/],["cómo voy",/📈 así vas/],["mi progreso",/📈 así vas/],["cómo voy en mates",/🎓 tus notas/],["resumen de hoy",/📅 tu día/],["mañana tengo colegio",/descansar|descansado|a dormir/],["tengo tarea",/te ayudo con la tarea/],["practicar restas",/🧮 ¿cuánto es \d+ - \d+/],["me rindo",/./],["repasar las tablas",/✖️ tabla del/],["cuánto es 25 x 4 tarea",/= 100/],
  ["wally abre jurassic",/abriendo|dime cuál/],["hey wally cuánto es 2+2",/= 4/],["oye wally",/dime, agente|aquí estoy|oídos/],["hola wally",/agente/],["quiero que me cantes",/soy WALLY/],["juguemos a adivinar",/1 al 100/],["me rindo",/era \d+/],["jugar a las adivinanzas",/🧠 adivinanza/],["me rindo",/era «/],["vamos a jugar a piedra papel tijera",/di 'piedra'/],["cuentos",/érase una vez/],["datos curiosos",/🧠 ¿sabías que/],["examen",/🧠 trivia/],["a",/./],["juego de inglés",/🇬🇧 quiz/],["me rindo",/en inglés es/],["palabras",/juegos de palabras/],["animales",/🐾/],["el dinosaurio más grande",/Argentinosaurus/],["cuál es tu dinosaurio favorito",/T-rex de JURASSIC/],
  ["wally cuéntame de ti",/soy WALLY/],["hay multijugador",/👥 EDTU es de un jugador/],["puedo jugar con mi hermano",/👥/],["mi hermano juega mejor",/rétalo/],["mi mamá me dijo que parara",/hazles caso/],["ranking",/🏆 en EDTU el ranking/],["récord de scream",/./],["cuántos metros hice",/./],["mis kills",/./],
  ["cuántos minutos faltan para las 8",/⏰ para las 8:00 faltan/],["qué hora es en 2 horas",/serán las \d+:\d\d/],["cuánto falta para mañana",/🌙 para mañana faltan/],["qué día es el 25 de diciembre",/📅 el 25 de diciembre de \d{4} es (lunes|martes|miércoles|jueves|viernes|sábado|domingo)/],["cuántos días hasta el 18 de septiembre",/faltan \d+ días? \(cae en/],["cuántos días tiene septiembre",/septiembre tiene 30 días/],["qué mes viene después de agosto",/viene septiembre/],["cuántas semanas faltan para navidad",/semanas? \(\d+ días\) para navidad/],["cuántos días faltan para navidad",/🎄 faltan \d+ días para navidad/],["cuántos años tengo",/tienes 11 años|aún no me lo has dicho/],["cuándo es mi cumpleaños",/🎂/],["mi cumple es el 5 de mayo",/apuntado/],["en qué día cae mi cumpleaños",/🎂 tu cumpleaños cae en/],["mi cumpleaños es en marzo",/qué día de marzo/],["hoy es mi cumpleaños",/FELIZ CUMPLEAÑOS/],["feliz cumpleaños a mí",/FELIZ CUMPLEAÑOS/],["es fin de semana",/✅|❌/],["qué día de la semana es",/📅 hoy es/],["qué estación es",/🗓️ en Chile estamos en/],["hace calor",/🌤️/],
  ["qué",/completa la pregunta/],["por qué",/completa la pregunta/],["sí o no",/🎱 bola mágica/],["quizás",/🎱 bola mágica/],["bola mágica ¿ganaré hoy?",/🎱/],["no sé qué preguntar",/💡 idea/],["pregúntame tú",/💡 idea/],["cheats",/no hay trampas/],["vidas infinitas",/no hay trampas/],["nitro infinito",/no hay trampas/],["cómo hago trampa",/no hay trampas/],["quiz de mates",/🧮/],["me rindo",/./],
  ["hola soy david",/encantado, David/],["cómo me llamo",/te llamas David/],["hola me llamo sofía",/encantado, Sofía/],["yo soy david",/encantado, David/],["no soy david",/perdón/],["llámame capitán",/a la orden, Capitán/],["cómo me llamo",/te llamas Capitán/],["llámame agente",/a la orden, agente/],["soy espía",/te digo «agente»/],["soy un robot",/otro robot/],["eres real",/tan real como el código/],["me extrañaste",/💛|🥹|🤖/],["tienes familia",/mi familia es EDTU/],["david es tu papá",/mi familia es EDTU/],["cuál fue mi última pregunta",/🧠/],["soy el hermano de david",/VIP/],["olvida mi nombre",/agente/],
  ["cuánto es 7 dividido en 2",/= 3\.5/],["cuánto es 2 a la 5",/= 32/],["cuánto es 15 por ciento de 80",/= 12/],["cuánto es el 20 por ciento de 50",/= 10/],["cuánto es un cuarto de 100",/= 25/],["cuánto es un tercio de 90",/= 30/],["cuánto es la raíz de 49",/= 7/],["cuánto es 5 factorial",/= 120/],["cuántos ceros tiene un millón",/6 ceros/],["cuánto es un millón por dos",/= 2000000/],["cómo se escribe 1000 en letras",/«mil»/],["escribe mil",/«mil»/],["345 en letras",/trescientos cuarenta y cinco/],["qué número sigue después de 99",/viene el 100/],["cuenta de 2 en 2 hasta 10",/2, 4, 6, 8, 10/],["cuenta hacia atrás desde 5",/5\.\.\. 4\.\.\. 3/],["tabla del 7 hasta el 12",/7×12=84/],["es primo el 7",/✅ sí, 7 es primo/],["es par el 9",/❌ no, 9 no es par/],["números primos",/2, 3, 5, 7, 11/],["redondea 3.7",/redondeado es 4/],["cuál es mayor 5 o 7",/7 es mayor/],["ordena 3 1 2",/1, 2, 3/],["suma 1 2 3 4 5",/= 15/],
  ["cuántos continentes hay",/🌍/],["cuál es el océano más grande",/Pacífico/],["por qué llueve",/🌧️/],["qué es un volcán",/🌋/],["de qué color es la sangre",/roja/],["cuál es el pájaro más grande",/avestruz/],["por qué hay día y noche",/24 horas/],["hay vida en marte",/Perseverance/],["quién inventó el avión",/Wright/],["cuántas personas viven en chile",/20 millones/],["cuánto mide la torre eiffel",/330/],["quién pintó la mona lisa",/Leonardo/],["cuántos jugadores tiene un equipo de fútbol",/11 jugadores/],["por qué flotan los astronautas",/🧑‍🚀/],
  ["existen los espías",/Misión Imposible/],["cuál es tu película favorita",/WALL·E/],["qué música te gusta",/beeps/],["conoces minecraft",/de oídas/],["quién es messi",/Argentina/],["quién ganó el mundial",/2022/],["eres del colo colo",/no me meto/],["quién es batman",/gadgets/],["puedes volar",/casi/],["cómo eres",/◉‿◉/],["dibuja un dino",/🦖 🦖 🦖/],["haz una cara feliz",/😊/],["muéstrame un corazón",/❤️/],
  ["hola en francés",/bonjour/],["cómo se dice gracias en japonés",/arigat/],["gato en portugués",/«gato»/],["los días de la semana en inglés",/Monday/],["cómo se dice lunes en inglés",/monday/],["cuenta hasta 10 en inglés",/one, two/],["el abecedario",/27 letras/],["cuántas vocales hay",/5 vocales/],["qué es un verbo",/VERBO/],["sinónimo de feliz",/contento/],["antónimo de grande",/pequeño/],["rima con gato",/pato|plato|zapato/],["qué significa nag",/NOT A GAME/],["qué significa lol",/carcajadas/],["qué significa drs",/Drag Reduction/],["haber o a ver",/veamos/],["lleva tilde",/AGUDAS/],["cómo se escribe correctamente",/ortografía de espía/],["deletrea dino",/D - I - N - O/],
  ["tengo hambre",/🍎/],["tengo sed",/💧/],["estoy enfermo",/adulto/],["me corté",/131|adulto/],["me perdí en el mall",/133/],["hay un extraño",/NO te vayas/],["me hacen bullying",/147/],["nadie me quiere",/NO estás solo/],["hay un monstruo",/NOT A GAME/],["no puedo dormir",/respira/],["mi mascota murió",/lo siento/],["mis papás pelean",/NADA de eso es tu culpa/],["odio el colegio",/de a uno/],["odio las mates",/quiz de mates fácil/],["saqué mala nota",/no te definen/],["necesito hablar",/escucharte/],
  ["qué es la amistad",/🤝/],["qué es un sueño",/🌙/],["cómo hago amigos",/🌱/],["cómo ser mejor en los juegos",/🏋️/],["cómo mejoro",/🏋️/],["motívame",/🌟/],["frase del día",/🌟/],["tengo flojera",/antiflojera/],["cuánto tiempo puedo jugar",/⏱️/],["los videojuegos son malos",/⏱️/],["palabra del día",/🔤 palabra del día/],["dato del día",/🧠 dato del día/],["cuál es el plan",/📋 plan de espía/],["organiza mi tarde",/📋/],
  ["cómo se hace un robot",/sensores/],["tienes corazón",/píxeles/],["tienes sentimientos",/REAL/],["qué sueñas",/🌙/],["qué piensas de mí",/gran espía/],["te equivocaste",/me equivoco/],["tienes razón",/orgullo/],["mentira",/no sé mentir/],["prométeme",/prometido/],["trato hecho",/trato hecho/],["abrázame",/abrazo robótico/],["choca",/choca esos circuitos/],["cambio y fuera",/cambio y fuera/],["misión cumplida",/misión cumplida/],["apágate",/botón de apagado/],
  ["dónde está el lago",/🏞️/],["cómo escapo",/trucos de SCREAM/],["qué hace la vitrola",/hipnotiza/],["qué pasa si apago la linterna",/sigilo/],["quién es el doctor vz",/Dr\. VZ/],["qué son los sectores",/⏱️/],["qué pasa si le gano a la ia",/victoria/],
  ["holaaaa",/agente/],["holiwis",/agente/],["buenaaas",/agente/],["hooola",/agente/],["nooo",/sin problema|cambias|entendido/],["xdxd",/reír|risa|jaja/],["okk",/^(?!.*(no entendí|circuitos no|confundido))/],["vaaale",/^(?!.*(no entendí|circuitos no|confundido))/],["chaooo",/^(?!.*(no entendí|circuitos no|confundido))/],["porfa",/¡claro que sí/],["q",/completa la pregunta/],["xq",/completa la pregunta/],["tqm",/💛|mejor espía/],["bn",/me alegro|anotado|gracias por/],["ntp",/tranqui/],["tb",/también/],["salu2",/agente/],["d nada",/gracias a ti/],["cuanto es 2+2 porfa",/= 4/],["abre jurassic plis",/abriendo|dime cuál/],
  ["dime la hora y un chiste",/🕐.*‖/],["cuánto es 2+2 y 3+3",/= 4 ‖ 🧮 3\+3 = 6/],["1+1 y 2+2",/= 2 ‖ 🧮 2\+2 = 4/],["hola y adiós",/‖/],["primero un chiste después la hora",/‖ 🕐/],["un chiste, porfa, y la hora",/‖ 🕐/],["nombre: david",/encantado, David/],["edad: 11",/11 años/],["cumpleaños: 14 de marzo",/apuntado/],["abre: f1",/abriendo|dime cuál/],["elige entre jurassic y scream",/JURASSIC|SCREAM/],["piedra papel y tijera",/di 'piedra'/],["olvida mi nombre",/agente/],
  ["chiste de mates",/problemas/],["chiste de perros",/taladrando/],["chiste de profesores",/lápiz/],["chiste sobre ti",/escondidas/],["cuál es el colmo de un robot",/batería/],["colmo",/colmo de un/],["qué le dijo un dino a otro",/cola/],["toc toc",/quién es/],["wally",/qué\?/],["wally-nte",/buenísimo/],["yo veo algo azul",/cielo/],["simón dice salta",/Simón dice: ¡salta!/],["lagarto",/Big Bang/],["tres en raya",/abre gato/],["adivina adivinador",/🧠 adivinanza/],["me rindo",/era «/],["ahorcado en el chat",/🪝 AHORCADO: _/],["a",/✅|❌|🤔/],["e",/✅|❌|🤔/],["me rindo",/🪝 era «/],
  ["cuántas horas duermes",/mi rutina/],["a qué hora debo dormir",/9-11 horas/],["es sano comer dulces",/🍬/],["cuánta agua debo tomar",/💧/],["por qué hay que lavarse los dientes",/🦷/],["ideas para jugar afuera",/🌳/],["juegos sin pantalla",/🎒/],["llueve y no puedo salir",/🌧️/],["manualidades",/✂️/],["experimento fácil",/🔬/],["cómo hago un volcán",/bicarbonato/],["cómo hago un avión de papel",/✈️/],["cómo hago panqueques",/🥞/],["puedo cocinar solo",/👩‍🍳/],["reglas de seguridad",/🦺/],["puedo dar mi dirección",/NUNCA/],["alguien me pide fotos",/147/],["contraseña segura",/🔑/],["olvidé mi pin",/superadmin/],
  ["quién te programa de noche",/Claude/],["eres claude",/soy WALLY/],["cómo aprendes",/no aprendo solo/],["cuál fue tu primera mejora",/este chat/],["cuántas preguntas te han hecho",/💬 en este navegador/],["tienes otros usuarios",/🔒/],["cuántos agentes hay",/👥/],["qué es una misión en edtu",/🎯 en el centro de mando/],["el centro de mando",/🛰️ el CENTRO DE MANDO/],["cómo creo un agente",/pestaña 👥/],["qué es el pin",/🔐 el PIN/],["qué es el reconocimiento facial",/🧬/],["dónde se guardan los datos",/localStorage/],["es seguro edtu",/💾/],
  ["el carrito de david",/LAFVIN/],["qué es lafvin",/LAFVIN/],["cómo conecto el mando",/🎮 mando/],["robótica",/🤖 la robótica/],["qué es arduino",/🔌 Arduino/],["qué es un sensor",/👀/],["cómo prendo un led",/digitalWrite/],["qué es scratch",/bloques/],["qué lenguaje aprendo primero",/Scratch/],["haz un juego para mí",/buzón/],["qué juego nuevo viene",/🔮/],["dile a david que ponga un juego de barcos",/apuntado en el buzón/],["tengo una idea",/dime tu idea/],["idea: más dinos en jurassic",/apuntado en el buzón.*2 ideas/],["quiero hablar con david",/👨‍💻 David es mi creador/],["quiero un juego de carreras de barcos",/apuntado en el buzón/],
  ["mis ideas",/📮 buzón de ideas \(\d+\)/],["lee el buzón",/📮/],["borra mis ideas",/buzón de ideas vaciado/],["buzón",/vacío/],["volver al menú",/🚪 cerrando la Sala/],["cerrar",/🚪/],["inicio",/🚪/],["abre el chat",/💬 el canal de comunicaciones/],["tengo mensajes",/💬/],["mi perfil",/👤 tu perfil/],["cambiar foto de perfil",/👤/],["ver agentes",/pestañas del centro de mando/],["permiso de cámara",/🎥🎤/],["micrófono no funciona",/🎥🎤/],["borra todo",/cosa seria/],
  ["cuánto mide la pista",/infinita/],["qué auto es",/RB18/],["quién es max verstappen",/campeón/],["mi velocidad máxima",/🏎️ tus marcas de F1/],["cuántas carreras llevo",/🏎️ tus totales de F1/],["mi mejor carrera",/🏎️ tus marcas de F1/],["cómo tomo las curvas",/frena ANTES/],["choqué",/💥/],["quién es el kóndor",/🦅 el KÓNDOR/],["kóndor",/🦅/],["cómo vencer al kóndor",/nitro cargado/],["el fantasma me ganó",/👻 tu fantasma/],["qué es el modo espectador",/VER MI RÉCORD/],
  ["cómo sobrevivo la primera noche",/guía del día 1/],["por dónde empiezo en la isla",/guía del día 1/],["dónde está el refugio",/🏠 el refugio/],["qué como en jurassic",/🍽️/],["me estoy muriendo de hambre en el juego",/🍽️/],["me muero de hambre",/🍎/],["los dinos son amigos",/PTERO BEBÉ/],["el dino me persigue",/🩹/],["sobreviví 7 días",/🏆 JURASSIC termina|los 7 días/],["hay día 8",/no hay día 8/],["chiste",/./],["ríete",/./],["serie de dinos",/^(?!.*(médico|batería|binario|circuitos!))/],
  ["por dónde empiezo en scream",/guía de SCREAM/],["qué hago primero en scream",/guía de SCREAM/],["cuántos pisos hay",/7 pisos/],["el ascensor",/🛗/],["la araña me sigue",/🕷️ la araña/],["cómo me escondo",/🤫/],["cuánto tiempo me queda",/20 minutos/],["dónde está el reloj dorado",/\+60 segundos/],["se fue la luz",/⚡ el generador/],["qué es un escape fantasma",/0 apariciones/],["guía de nag",/guía de NOT A GAME/],["los cajones están vacíos",/🗄️/],
  ["cómo se juega el cubo",/guía del CUBO/],["cómo armo el cubo",/capa por capa/],["cuántas caras tiene",/6 caras/],["cómo giro el cubo",/🔄 para girar/],["qué es una revoltura",/🔀/],["qué dificultades hay",/🎚️/],["pista del cubo",/💡 en el CUBO/],["cuál es el mínimo de giros",/número de Dios/],
  ["reglas del ajedrez",/JAQUE MATE/],["cómo mueve el caballo",/en L/],["cómo hago un gol",/⚽/],["cómo gano en 2048",/esquina/],["qué significan los números del buscaminas",/8 casillas/],["cómo se juega conecta 4",/CONECTA 4/],["cuál minijuego es más difícil",/😈/],["cuál minijuego me recomiendas",/😊 para empezar/],["hay ia en el gato",/🤖 sí/],["el ajedrez es muy difícil",/♟️ AJEDREZ/],["récord de snake",/🕹️/],["cómo se juega snake",/Snake|SNAKE/],
  ["cuáles son los 21 logros",/los 21 logros de EDTU/],["lista de logros",/llevas \d+ de 21/],["qué logros me faltan",/te faltan \d+/],["logro de f1",/logros de F1/],["cómo se juega conecta 4",/CONECTA 4/],
  ["dónde están los wallys",/4 WALLYs escondidos/],["cuántos wallys encontré",/\d de 4/],["cómo consigo el huevo",/🥚/],["soy leyenda",/LEYENDA de EDTU/],["cómo desbloqueo el cubo de oro",/👑/],["hay más secretos",/🤫 secretos de EDTU/],["qué esconde el logo",/logo de EDTU/],["dificultades de scream",/PESADILLA/],["qué es extinción",/EXTINCIÓN/],["cómo desbloqueo infierno",/🎚️/],
  ["quién ganó el reto",/MÁS en el mismo desafío/],["cuántos retos envié",/⚔️ retos: \d+ enviado/],["me mandaron un link",/📥/],["el link no funciona",/🔗 si el link/],["cuál es la página",/www\.edtu\.cl/],["invitar a un amigo a edtu",/👋 invitar/],["perdí la racha",/🔥 la racha/],["qué pasa si no juego un día",/vuelve a 0/],["qué desafío hay hoy en f1",/🎯 cada mundo/],
  ["chiste de wally",/escondidas/],["cuento de terror",/📖👻/],["cuento para dormir",/📖🌙/],["cuento de wally",/📖🤖/],["otro cuento",/📖/],["el cuento estuvo bueno",/otro cuento/],["otro chiste",/./],["otra adivinanza",/🧠 adivinanza/],["me rindo",/era «/],["aplausos",/reverencia/],["eres un genio",/reverencia/],["te doy 10 puntos",/10 de 10/],["5 estrellas",/5 de 5/],["nota 7",/7 de 10/],["inventa una historia conmigo",/tú empiezas/],["había una vez un dino que quería volar",/📖 \.\.\./],["y entonces se encontró con wally",/turno 3/],["fin",/FIN 🌟.*2 turnos/],
  ["acabo de jugar jurassic",/cómo te fue en JURASSIC/],["terminé la carrera",/cómo te fue/],["hice 1200 metros en f1",/🏎️ ¡1200 metros!/],["sobreviví 3 días",/faltan 4/],["junté 4 pistas",/faltan 3/],["maté 30 zombies",/¡25! logro/],["escapé en 15 minutos",/🕷️ ¡escapaste en 15/],["batí mi récord",/🏆 ¡GRANDE/],["casi lo logro",/💪 «casi»/],["una más",/una más y a descansar/],["5 minutos más",/una más y a descansar/],["mañana lo intento",/🌙/],["mamá dice que me vaya",/hazle caso/],
  ["por qué tiembla",/placa de Nazca/],["qué hago si tiembla",/🚨 si tiembla/],["qué es un tsunami",/🌊/],["quién fue o higgins",/padre de la patria/],["quién fue arturo prat",/Esmeralda/],["qué pasó el 18 de septiembre",/Primera Junta/],["qué es la cueca",/💃/],["cómo se hace un volantín",/🪁/],["qué es una empanada",/🥟/],["cuántas regiones hay",/16 regiones/],["cuántas estrellas tiene la bandera",/UNA estrella/],["qué es el copihue",/🌺/],["el cóndor",/🦅/],["te gusta el colegio",/🏫/],
  ["sabes cuánto es 5 por 5",/= 25/],["sabes contar",/🔢 ¡claro!/],["sabes leer",/📖 leo/],["sabes dibujar",/🎨/],["sabes hablar inglés",/🇬🇧 a little/],["sabes de dinosaurios",/🦖 ¡mucho!/],["sabes historia",/O'Higgins/],["sabes todo",/casi/],["no sabes nada",/pruébame/],["sabes dónde vivo",/🔒/],["qué no sabes",/lo que NO sé/],["cuál es tu debilidad",/debilidades/],["qué te da miedo",/😱/],["qué te hace feliz",/😊 me hace feliz/],["qué te enoja",/😤/],["adivinanza",/🧠 adivinanza/],["sabes cuentos",/📖 ¡muchos!/],["me rindo",/era «/],
  ["chiste de fantasmas",/👻/],["chiste de piratas",/ARRR/],["chiste de números",/cinturón/],["chiste de celulares",/contactos/],["chiste chileno",/tiemble/],["chiste de messi",/arco/],["chiste de la escuela",/esqueleto/],["chiste del día",/📅 chiste del día/],["chiste corto",/átomo/],["chiste largo",/jirafa/],["ya me lo contaste",/uno nuevo/],["cuál es tu chiste favorito",/escondidas/],["chiste de arañas",/busca la web/],["te cuento un chiste",/🎤/],["por qué el pollo cruzó la calle? para llegar al otro lado",/jajaja|JAJAJA/i],["tengo un secreto",/soy una tumba/],["cuántos chistes sabes",/chiste del día/],
  ["cómo funcionas",/⚙️/],["de qué estás hecho",/código/],["tienes batería",/🔋/],["te cargas",/🔋/],["necesitas dormir",/😴/],["tienes hambre",/🍪/],["puedes llorar",/🥲/],["puedes reír",/beep-jaja/],["cuál es tu apellido",/📛/],["por qué te llamas wally",/🏷️/],["eres niño o niña",/robot/],["cuánto mides",/📏/],["de qué color son tus ojos",/LEDs/],["tienes pelo",/metálico/],
  ["me encanta edtu",/le encantas a EDTU/],["edtu es lo mejor",/le encantas/],["me gusta scream",/a mí también/],["odio scream",/linterna PRENDIDA/],["scream es fácil",/😏 ¿fácil\?/],["jurassic es aburrido",/DESAFÍO DEL DÍA/],["el cubo es imposible",/cruz blanca/],["f1 es lo mejor",/vroom/],["nag es lo más difícil",/helipuerto/],["ya me aburrí",/😴 ¿aburrido/],["me cansé",/😴/],["es muy fácil",/😏/],["es muy difícil",/respira|imposible|casi/],["se me cerró el juego",/🛠️ soporte/],
  ["no entiendo las fracciones",/🍕/],["qué es un porcentaje",/💯/],["qué es un número primo",/1 y por sí mismo/],["múltiplos de 7",/7, 14, 21/],["divisores de 12",/1, 2, 3, 4, 6, 12/],["divisores de 17",/es primo/],["qué es el perímetro",/borde/],["área de un cuadrado de lado 5",/= 25/],["perímetro de un rectángulo de 3 por 4",/= 14/],["área de un triángulo de base 6 y altura 4",/= 12/],["área de un círculo de radio 2",/12\.57/],["cuántos grados tiene un triángulo",/180°/],["qué es un ángulo recto",/90°/],["cuántas sílabas tiene dinosaurio",/4 sílabas: di-no-sau-rio/],["separa en sílabas elefante",/e-le-fan-te/],["cuántas sílabas tiene murciélago",/mur-cié-la-go/],["cuántas sílabas tiene país",/pa-ís/],["cuántas sílabas tiene transporte",/trans-por-te/],["qué es un sinónimo",/significa lo mismo/],["qué es un párrafo",/📝/],["qué es un mamífero",/🐶/],["qué es un insecto",/6 patas/],["qué es un átomo",/⚛️/],["cuáles son los estados de la materia",/SÓLIDO/],["de qué está hecho el agua",/H₂O/],["qué es un ecosistema",/🌳/],
  ["el planeta más grande",/Júpiter/],["el planeta más caliente",/Venus/],["cómo se forman las nubes",/☁️/],["qué es el arcoíris",/🌈/],["qué es un huracán",/🌀/],["por qué la luna cambia",/🌙/],["a qué distancia está la luna",/384\.000/],["cuántos huesos tiene el cuerpo",/206/],["cuántos dientes tenemos",/20 dientes de leche/],["por qué bostezamos",/🥱/],["por qué soñamos",/💭/],["cuánto mide una ballena",/30 metros/],["qué comen los pingüinos",/krill/],["dónde viven los osos polares",/Ártico/],["qué es el calentamiento global",/🌡️/],["cómo cuido el planeta",/🌍 para cuidar/],["qué es reciclar",/♻️ reciclar/],["qué va en el basurero verde",/vidrio/],["cómo ahorro agua",/🚿/],
  ["mi amigo me pegó",/🛑/],["me peleé con mi mejor amigo",/peleas entre amigos/],["mi hermano me molesta",/😤/],["tengo prueba mañana",/📚 plan de estudio/],["tengo un examen y no estudié",/aún hay tiempo/],["cómo me concentro",/📚/],["no quiero ir al colegio",/😔/],["me da vergüenza hablar en clase",/🦁/],["cómo dejo de ser tímido",/🦁/],["cómo pido disculpas",/🙏/],["me gusta alguien",/💘/],["se ríen de mí",/NO es tu culpa/],["mi profe me odia",/🍎/],["perdí mi celular",/🔍/],["rompí algo de mi mamá",/lo valiente es contarlo/],["mentí",/lo valiente es contarlo/],["cómo controlo la rabia",/🌬️/],["estoy celoso",/💚/],["nos cambiamos de casa",/📦/],
  ["rekord",/quisiste decir 'récord'/],["adivinansa",/quisiste decir 'adivinanza'/],["asdfgh",/no entendí|circuitos|confundido/],
];
let ok=0, bad=0;
for(const [q,re] of T){ let r=""; try{ window._wallyPrevQ=store.edtu_wally_last||""; r=String(fn(q)); store.edtu_wally_last=q.slice(0,40); }catch(e){ r="❌ EXCEPCIÓN: "+e.message; }
  const p=re.test(r) && !/error de circuitos/.test(r); if(p) ok++; else bad++; console.log((p?"✅ ":"❌ ")+q.padEnd(30)+" → "+r.replace(/\n/g," ").slice(0,90)); }
for(const k of ["_wallyGuess","_wallyRiddle","_wallyEng","_wallyTrivia","_wallyMath","_wallyRound"]){ if(window[k]){ bad++; console.log("❌ estado activo al final de la lista: "+k+" (cierra la secuencia en el test)"); } }
let fz=0; const AL="abcdefghijklmnñopqrstuvwxyzáéíóú0123456789 ?¿!¡+-*/.,'🎲🧠🦖  ";
for(let i=0;i<60;i++){ const len=1+Math.floor(Math.random()*24); let q=""; for(let j=0;j<len;j++) q+=AL[Math.floor(Math.random()*AL.length)]; try{ window._wallyPrevQ=""; const r=fn(q); if(typeof r!=="string"||!r.length) throw new Error("respuesta vacía o no-string"); if(/error de circuitos/.test(r)) throw new Error("excepción interna (error de circuitos)"); fz++; }catch(e){ bad++; console.log("❌ fuzz «"+q+"» → "+e.message); } }
console.log("🎲 fuzz: "+fz+"/60 entradas aleatorias sin excepciones");
console.log("\n"+ok+" OK · "+bad+" fallos · "+T.length+" preguntas");
process.exit(bad?1:0);
